# Change these first
owner: minc-nice-100 # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: 主站
    url: https://ited.top
    maxResponseTime: 6000
    __dangerous__body_down: "不对劲... 是时候翻遍日志，并在堆栈跟踪中找出问题所在了"
  - name: 心理分站
    url: https://yy.ited.top
    maxResponseTime: 6000
    __dangerous__body_down: "不对劲... 是时候翻遍日志，并在堆栈跟踪中找出问题所在了"
  - name: Telegraph图床（上传）
    url: https://oss.ited.top/
    maxResponseTime: 6000
    __dangerous__body_down: "不对劲... 是时候翻遍日志，并在堆栈跟踪中找出问题所在了"
  - name: Telegraph图床（下载）
    url: https://oss.ited.top/file/361528033f3e5fcb7c5c4.gif
    maxResponseTime: 6000
    __dangerous__body_down: "不对劲... 是时候翻遍日志，并在堆栈跟踪中找出问题所在了"
  - name: 网盘
    url: https://pan.ited.top/
    maxResponseTime: 6000
    __dangerous__body_down: "不对劲... 是时候翻遍日志，并在堆栈跟踪中找出问题所在了"
  - name: 公共文件站
    url: https://public.ited.top/
    maxResponseTime: 6000
    __dangerous__body_down: "不对劲... 是时候翻遍日志，并在堆栈跟踪中找出问题所在了"
  - name: 文档站
    url: https://docs.ited.top/
    maxResponseTime: 6000
    __dangerous__body_down: "不对劲... 是时候翻遍日志，并在堆栈跟踪中找出问题所在了"
  - name: 系统状态
    url: https://on.ited.top/
    maxResponseTime: 6000
    __dangerous__body_down: "不对劲... 是时候翻遍日志，并在堆栈跟踪中找出问题所在了"
  - name: B2储存桶
    url: https://b2.ited.top/0.gif
    maxResponseTime: 6000
    __dangerous__body_down: "不对劲... 是时候翻遍日志，并在堆栈跟踪中找出问题所在了"

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: on.ited.top
  # baseUrl: /your-repo-name
  logoUrl: https://lib.ited.top/favicon.ico
  name: 状态 - ited博客
  introTitle: "这是ited博客的业务状态页，同时也是一个网址导航"
  introMessage: 此业务托管于github
  navbar:
    - title: 首页
      href: /
    - title: 主站
      href: https://ited.top
    - title: 隐私政策
      href: https://ited.top/privacy-policy.html

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
